# Generated by Django 3.1.13 on 2021-09-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_make_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.RemoveField(
            model_name='article',
            name='watch_list',
        ),
        migrations.AlterField(
            model_name='article',
            name='last_modify',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
