# Generated by Django 3.1.13 on 2021-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_revise_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
